### ISSUE TITLE
Improved rendering settings

### ISSUE THREAD

**Issue by TheBoneJarmer** [grizzlei/nle#2]
Hey,

I was browsing your code and I noticed something in https://github.com/grizzlei/nle/blob/69f1a59d002de9a687e86aa777a1fd3085bec099/src/nle/Renderer3D.cpp#L103

Your method seems to lack some stuff that disable back-culling and enable transparent textures. I will share what I use so you can see for yourself:

```cpp
glEnable(GL_BLEND); // Enables the blending functionality
glEnable(GL_CULL_FACE); // Disables rendering of faces not visible to the camera, increases performance
glCullFace(GL_BACK); // Decides what face to hide for the camera, only works when GL_CULL_FACE is enabled
glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA); // Dunno how this works, it just makes sure transparency in textures are done right :p

glClearColor(this->clear_color.r / 255.0, this->clear_color.g / 255.0, this->clear_color.b / 255.0, this->clear_color.a / 255.0); // My clear functions start here
glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT); // Veerrry important to allow both for texture blending

// Render 3D shit
```

Hope it helps!

**Comment by grizzlei** [comment]
Hello @TheBoneJarmer thank you for your attention.

`GL_BLEND` will be enabled and disabled per object, but yes, we still need it somewhere in the `Render3D::render()` function.

I added set_clear_color member function to Renderer3D, will be included in the next commit.

`GL_CULL_FACE` and `GL_DEPTH_BUFFER_BIT` are needed indeed. 

Thanks for the heads up.

**Comment by TheBoneJarmer** [comment]
Hey, no biggie. Glad I could help! ^_^
